-- UI Templates Restructured by Type and Alphabetically
local templates = {
    -- Buttons
    Button = {
        "ActionButtonTemplate",
        "BackpackButtonTemplate",
        "CalendarBackdropTemplate",
        "CalendarDayButtonTemplate",
        "CalendarEventButtonTemplate",
        "CalendarFilterButtonTemplate",
        "CalendarHolidayButtonTemplate",
        "CalendarNextMonthButtonTemplate",
        "CalendarPrevMonthButtonTemplate",
        "CharacterCreateButtonTemplate",
        "CharacterItemButtonTemplate",
        "ChatFrameChannelButtonTemplate",
        "ChatFrameTabButtonTemplate",
        "CloseButtonTemplate",
        "ColorPickerOkayButtonTemplate",
        "ColorPickerCancelButtonTemplate",
        "ColorSwatchTemplate",
        "CooldownFrameTemplate",
        "CraftingPageButtonTemplate",
        "EditBoxTemplate",
        "EquipmentManagerCostFrameTemplate",
        "EquipmentManagerItemButtonTemplate",
        "EquipmentSetButtonTemplate",
        "FactionButtonTemplate",
        "FlightMapButtonTemplate",
        "FriendsFrameButtonTemplate",
        "GameTooltipButtonTemplate",
        "GatherResourcesButtonTemplate",
        "GuildBankMoneyButtonTemplate",
        "InspectButtonTemplate",
        "JournalTabButtonTemplate",
        "MailButtonTemplate",
        "MailItemButtonTemplate",
        "MapPoiButtonTemplate",
        "MerchantItemButtonTemplate",
        "MinimapButtonTemplate",
        "MinimapZoomInButtonTemplate",
        "MinimapZoomOutButtonTemplate",
        "MoneyFrameTemplate",
        "MultiActionContainerButtonTemplate",
        "MultiActionBarTemplate",
        "NewItemButtonTemplate",
        "ObjectiveTrackerButtonTemplate",
        "OutlineQuestButtonTemplate",
        "PetActionBarButtonTemplate",
        "PlayerTalentButtonTemplate",
        "PVEFrameTabButtonTemplate",
        "QuestLogTitleButtonTemplate",
        "QuestRewardButtonTemplate",
        "RaidTargetButtonTemplate",
        "ReagentButtonTemplate",
        "RecycleItemButtonTemplate",
        "ReskinButtonTemplate",
        "ScrollOfResurrectionButtonTemplate",
        "ServerInfoButtonTemplate",
        "ShoppingTooltipButtonTemplate",
        "SocialQueueButtonTemplate",
        "SpellButtonTemplate",
        "SplitButtonTemplate",
        "StartDelayButtonTemplate",
        "StopButtonTemplate",
        "StyleCheckboxTemplate",
        "TalentFrameTabButtonTemplate",
        "TargetFrameButtonTemplate",
        "TaxiButtonTemplate",
        "TimeManagerButtonTemplate",
        "ToggleFrameButtonTemplate",
        "TravelPassButtonTemplate",
        "UnitPopupButtonTemplate",
        "WatchFrameButtonTemplate",
        "WorldMapButtonTemplate"
    },
    
    -- Frames
    Frame = {
        "BackdropTemplate",
        "CalendarBackdropTemplate",
        "CharacterCreateBackdropTemplate",
        "FloatingBattlePetTooltipTemplate",
        "GameTooltipTemplate",
        "GossipFrameTemplate",
        "MailFrameTemplate",
        "PlayerModelFrameTemplate",
        "PortraitFrameTemplate",
        "QuestInfoFrameTemplate",
        "QuestRewardFrameTemplate",
        "RaidTargetFrameTemplate",
        "ServerInfoFrameTemplate",
        "SpellBookFrameTemplate",
        "TalentFrameTemplate"
    },
    
    -- StatusBars
    StatusBar = {
        "BarMeterTemplate",
        "CastBarTemplate",
        "GlowingStatusBarTemplate",
        "HealthBarTemplate",
        "ManaBarTemplate",
        "ObjectiveTrackerStatusBarTemplate"
    },
    
    -- ScrollFrames
    ScrollFrame = {
        "AutoHeightScrollFrameTemplate",
        "AutoHeightScrollFrameWithScrollBar",
        "BackdropScrollFrameTemplate",
        "FloatingScrollFrameTemplate",
        "MagicScrollFrameTemplate",
        "QuestInfoRewardsFrameTemplate",
        "ScriptedScrollFrameTemplate"
    },
    
    -- Texture Elements
    Texture = {
        "BackgroundTextureTemplate",
        "BorderCornerTemplate",
        "BorderTemplate",
        "ButtonTextureTemplate",
        "ChatFrameTabTextureTemplate",
        "DialogBorderTemplate",
        "GlowTextureTemplate",
        "HorizontalBarTemplate",
        "IconBorderTemplate",
        "PortraitTextureTemplate",
        "ScrollBarTextureTemplate",
        "SlotTextureTemplate",
        "TextureTemplate",
        "VerticalBarTemplate"
    },
    
    -- Other Templates
    Other = {
        "AlwaysUpFrameTemplate",
        "ArenaEnemyFrameTemplate",
        "CharacterBackdropTemplate",
        "CharacterItemTemplate",
        "CompactUnitFrameTemplate",
        "CooldownOverlayTemplate",
        "EditBoxWithBorderTemplate",
        "EquipmentManagerItemSlotTemplate",
        "FontStringTemplate",
        "GossipIconTemplate",
        "ItemButtonTemplate",
        "MagicScrollChildTemplate",
        "MoneyInputFrameTemplate",
        "MoneyFrameTemplate",
        "PortraitTemplate",
        "ScrollingMessageFrameTemplate",
        "ScriptedFontStringTemplate",
        "SpellBookSkillLineTemplate",
        "TabTemplate",
        "TextureWithBackdrop",
        "UnitButtonTemplate"
    }
}

return templates